export { default as Paragraph } from "./paragraph/paragraph";
export { default as Title } from "./title/title";
export { default as Label } from "./label/label";
export { default as HeadingXXL } from "./heading/h1";
export { default as HeadingXL } from "./heading/h2";
export { default as HeadingLarge } from "./heading/h3";
export { default as HeadingMedium } from "./heading/h4";
export { default as HeadingSmall } from "./heading/h5";
export { default as HeadingXSmall } from "./heading/h6";
